### PR TITLE
EZS-117: Remove duplicate images in Demo bundle for the editor

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZS-117

This PR requires https://github.com/ezsystems/DemoBundle/pull/152 to be merged first.

### CODE REVIEW

**Comment by bdunogier** [comment]
+1

**Comment by lolautruche** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by michalpipa** [comment]
:+1:

**Comment by lserwatka** [comment]
+1

**Comment by bdunogier** [comment]
Are there enough +1 ? I'm not sure...

**Comment by clash82** [comment]
Only 5? I'm disappointed... :-)

**Pull request merged**
